steps:
  - name: ":node:"
    command: npm test
    plugins:
      - docker-compose#v3.5.0:
          run: app
      - xwlee/expandable#v1.0.2:
          files:
            - /path/to/file/1
            - /path/to/file/2
          directories:
            - /path/1
            - /path/2
          properties:
            Hirer.login_id: ENV.login_id # env value
            Hirer.password: ENV.password # env value
            Debug.level: error # literal value
