steps:
  - name: ":node:"
    command: npm test
    plugins:
      - docker-compose#v3.5.0:
          run: app
      - xwlee/expandable#v1.0.4:
          files:
            - index.js
          # directories:
          #   - /path/1
          #   - /path/2
          properties:
            HIRER_NAME: jshirer
    artifact_paths: index.js
